# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - cwtr-webfunctions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api' # path to the Azure Functions project
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Publish Project'
        shell: bash
        run: |
          dotnet publish '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}' \
            --configuration Release \
            --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: 'Create Deployment Zip'
        shell: bash
        run: |
          cd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          zip -r ${{ github.workspace }}/functions-deploy.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0ED06285A01B4AD59A18A354B7FCF70B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE4F3284FB074C0E80A185DBE9955DE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C46C4064F5934A81A3920BD0FE743FF7 }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v2
        with:
          app-name: 'cwtr-webfunctions'
          package: '${{ github.workspace }}/functions-deploy.zip'
          scm-do-build-during-deployment: false
          